config/routes.rb
Rails.application.routes.draw do

  resources :admin
  resources :schools do
    resources :trainings, except: [:index]
  end
  resources :trainings, only: [:index]

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, only: [:edit] do
    resources :pictures, only: [:create]
  end

  resources :comments

  root 'staticpages#home'

  get "/staticpages" => "staticpages#guide"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :training
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :training
end

app/models/school.rb
class School < ApplicationRecord
  has_many :trainings
  belongs_to :user 
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :training
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :school
  has_many :comments
  has_many :sessions
  has_many :programs

  acts_as_taggable_on :tags

  $modes = ["à distance", "présentiel", "à distance et en alternance", "à distance ou présentiel"]
  $durations = ["1-10", "11-20", "21-30", "31-40", "41+"]
  $prices = [ "0-1000", "1001-2000", "2001-3000", "3001-4000", "4000+"]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_one_attached :picture
  after_create :welcome_send

  has_one :school

  def full_name
    self.first_name + " " + self.last_name
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @user = User.find_by(id: current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :warning, :danger, :success, :info, :primary, :secondary, :light
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new

  end

  def create
    if current_user
      @comment = Comment.new(content: params[:content],user_id: current_user.id, training_id: params[:training_id])
      if @comment.save
        flash[:success] = "The comment has been added."
        redirect_to school_training_path(Training.find(params[:training_id]).school_id, params[:training_id])
      else
        flash[:danger] = "The comment has not been added."
        redirect_to school_training_path(Training.find(params[:training_id]).school_id, params[:training_id])
      end
    else
      flash[:danger] = "Connect to comment."
      redirect_to new_user_registration_path
    end
  end

  def edit
    @comment = Comment.find(params[:id])

  end

  def update
    @comments = Comment.all
    @comment = Comment.find(params[:id])
    @training = Training.find(@comment.training.id)
    if current_user
      @comment.update(content: params[:content])
      if @comment.save
        flash[:success] = "The comment has been edited."
        redirect_to school_training_path(params[:school_id], params[:training_id])
      else
        flash[:danger] = "The comment has not been edited."
        redirect_to school_training_path(params[:school_id], params[:training_id])
      end
    else
      flash[:danger] = "Connect to edit."
      redirect_to new_user_registration_path
    end
  end

  def index
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = "The comment has been deleted."
    redirect_to school_training_path(Training.find(params[:training_id]).school_id, params[:training_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    if params[:picture]
      @user = current_user
      @user.picture.attach(params[:picture])
      redirect_to edit_user_password_path
      flash[:success] = "Votre image de profil a été mise à jour."
    else
      flash[:danger] = "Vous n'avez pas inséré d'image."
      redirect_to edit_user_password_path
    end
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  def new
    @school = School.new
    if signed_in?
      if current_user.is_school === true
        redirect_to new_school_training_path(:school_id)
      end
    else
      redirect_to new_user_registration_path, info: "Pour renseigner vos formations en temps qu'école vous devez vous connecter ou vous inscrire."
    end
  end

  def create
    School.create(name: params[:school][:name], website: params[:school][:website], creation_year: params[:school][:creation_year].to_i, campus_nb: params[:school][:campus_nb].to_i, siret: params[:school][:siret], user_id: current_user.id)
    become_a_school
    @school = School.find_by(website: params[:school][:website])
    redirect_to new_school_training_path(@school.id), success: "Ce compte est désormais un compte École !"
  end

  private
  def become_a_school
    current_user.update(is_school: true)
  end


end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
	def guide
	end

  def home
  end
  
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController

  def index

    if params[:search]
      @filter = params[:search][:modes].concat(params[:search][:durations]).concat(params[:search][:prices]).flatten.reject(&:blank?)
      if @filter.empty?
        @trainings = Training.all
      elsif @filter.count == 1
        @trainings = Training.all.tagged_with(@filter, any: true)
      elsif @filter.count == 2
        @trainings = Training.all.tagged_with(@filter)
      elsif @filter.count == 3
        @trainings = Training.all.tagged_with(@filter, match_all: true)
      end
    else
      @trainings = Training.all
    end

    respond_to do |format|
      format.html
      format.js
    end
  end


  def show
    @training = Training.find(params[:id])
    @sessions = @training.sessions
    @programs = @training.programs
    @program = @programs.find_by(training_id: params[:id])
    @comments = @training.comments
  end

  def new

  end

  def create
    @school = current_user.school
    Training.create(school_id: @school.id, name: params[:training][:name] ,duration: params[:duration].to_i, description: params[:training][:description], hours_per_day: params[:hours_per_day].to_i,url: params[:training][:url], mode: params[:mode], help_for_a_job: true?(params[:help_for_a_job]) )
    redirect_to root_path, success: "Votre formation a bien été ajouté à notre catalogue !"
  end

private
  def true?(obj)
    obj == "true"
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/comments/_new_comment_form.html.erb
<%= form_tag "/comments", method: "post" do %>
  <input type="text" name="content" />
  <input type="submit" value="Envoyer" />
  <input type="hidden" name="training_id" value="<%= @training.id %>">
<% end %>

app/views/comments/edit.html.erb
<% if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |message| %>
      <p class="alert alert-danger d-flex justify-content-center" role="alert"><%= message %></p>
    <% end %>
<% end %>

<div class="container mt-5 form-group">
 <%= form_tag url_for(action: 'update'), method: "patch" do %>

      <strong><%= label_tag 'Contenu du commentaire' %></strong>
      <%= text_area_tag 'content', @comment.content, class:"form-control" %>
      <br />
      <%= hidden_field_tag "school_id", params[:school_id] %>
      <%= hidden_field_tag "training_id", params[:training_id] %>
      <div class="d-flex justify-content-center"><%= submit_tag "Editer le commentaire", class:"btn btn-success btn-lg"%></div>

    <% end %>
        <hr>
    <div style="margin-top: 10px;" class="d-flex justify-content-center"><%= link_to "Retour Accueil", root_path, :class => "btn btn-info btn-sm" %></div>
</div>

app/views/schools/create.html.erb
<h1>Schools#create</h1>
<p>Find me in app/views/schools/create.html.erb</p>

app/views/schools/new.html.erb
<div class="jumbotron text-center">
  <h2>Inscrivez votre école</h2>
  <div class="container col-6 mt-5 ">
    <div class="container bg-white col-8 rounded shadow p-3">
      <%= form_with model: @school do |form| %>
        <div class="form-group">
          <%= form.label :nom %>:<br />
          <%=form.text_field :name, class: 'form-control', placeholder: 'Nom de l\'école :'%>
        </div>
        <div class="form-group">
          <%= form.label 'Site internet de l\'école' %>:<br />
          <%=form.text_field :website, class: 'form-control', placeholder: 'www.mon_ecole.com'%>
        </div>
        <div class="form-group">
          <%= form.label 'Année de création :' %>:<br />
          <%=form.text_field :creation_year, class: 'form-control', placeholder: 'Ex: 1990'%>
        </div>
        <div class="form-group">
          <%= form.label 'Nombre de campus :' %>:<br />
          <%=form.text_field :campus_nb, class: 'form-control', placeholder: 'Ex: 3'%>
        </div>
        <div class="form-group">
          <%= form.label 'N° de Siret :' %>:<br />
          <%=form.text_field :campus_nb, class: 'form-control'%>
        </div>
          <hr>
        <div class="actions">
          <%= form.submit "Envoyer", class: 'btn btn-success' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/trainings/_comments.html.erb
<div class="bg-white rounded box-shadow">
  <h1 class="card text-center border-light col-xs-12  mb-3 pb-2 mb-0">Commentaires</h1>
  <% @training.comments.each do |comment| %>
    <div class= "d-flex flex-column comment">
      <div class="row comment_main">
        <div class="col user_avatar">
          <% if comment.user.picture.attached? %>
            <%= image_tag comment.user.picture %>
          <% else %>
            <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 64px; height: 64px;" src="https://previews.123rf.com/images/salamatik/salamatik1801/salamatik180100019/92979836-ic%C3%B4ne-de-visage-anonyme-de-profil-personne-silhouette-grise-avatar-par-d%C3%A9faut-masculin-photo-placeholder-.jpg" data-holder-rendered="true">
          <% end %>
        </div>
        <div class="col comment_author">
          <p><i class="fa fa-pencil"></i> <span class="user_name"><%= comment.user.full_name %></span></p>
        </div>
      </div>
      <div class="row">
        <div class="col comment_content">
          <%= comment.content %>
        </div>
      </div>
      <div class="row">

        <div class="col comment_details">
            <p><i class="fa fa-calendar"></i><%= comment.updated_at.strftime('%H:%M %d/%m/%y') %></p>
        </div

        <div class="col comment_buttons">
          <% if current_user %>
            <% if comment.user.id == current_user.id %>
              <%= form_tag comment_path(comment.id), method: "delete" do %>
                <%= hidden_field_tag "training_id", @training.id %>
                <%= hidden_field_tag "comment_id", comment.id %>
                <%= submit_tag "Supprimer" %>
              <% end %>
              <%= form_tag edit_comment_path(comment.id), method: "get" do %>
                <%= hidden_field_tag "school_id", @training.school.id %>
                <%= hidden_field_tag "training_id", @training.id %>
                <%= hidden_field_tag "comment_id", comment.id %>
                <%= submit_tag "Editer" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/trainings/_filter_mode.html.erb
<div class="container12">

  <%= simple_form_for :search, method: "GET", url: trainings_path, remote: true do |form|%>
    <div class="d-flex justify-content-center filters">
      <div class="text-center modes">
        <%= form.input :modes, label: "Mode", collection: $modes, as: :check_boxes %>
      </div>
      <div class="durations">
        <%= form.input :durations, label: "Durée (en semaines)", collection: $durations, as: :check_boxes %>
      </div>
      <div class="prices">
        <%= form.input :prices, label: "Prix", collection: $prices, as: :check_boxes %>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(function () {
    var chks_modes = $('[name="search[modes][]"]')
    var chks_durations = $('[name="search[durations][]"]')
    var chks_prices = $('[name="search[prices][]"]')
    //var checkBoxes = $("input.check_boxes");

    chks_modes.click(function () {
      for (i = 0; i < chks_modes.length; i++) {
        if ($(this)[0] !== chks_modes[i]) {
          chks_modes[i].checked = false;
        }
      }
    });
    chks_durations.click(function () {
      for (i = 0; i < chks_durations.length; i++) {
        if ($(this)[0] !== chks_durations[i]) {
          chks_durations[i].checked = false;
        }
      }
    });
    chks_prices.click(function () {
      for (i = 0; i < chks_prices.length; i++) {
        if ($(this)[0] !== chks_prices[i]) {
          chks_prices[i].checked = false;
        }
      }
    });

    checkBoxes[0].attributes.class.nodeValue = checkBoxes[0].attributes.class.nodeValue + " d-flex flex-column align-items-start";
    checkBoxes[6].attributes.class.nodeValue = checkBoxes[6].attributes.class.nodeValue + " d-flex flex-column align-items-start";
    checkBoxes[13].attributes.class.nodeValue = checkBoxes[13].attributes.class.nodeValue + " d-flex flex-column align-items-start";
   });
 </script>

app/views/trainings/_filters.html.erb
<div class="jumbotron">
  <h2 class="text-center">Tu cherches une formation en developpement web ? </h2>
  <hr>
    <%= simple_form_for :search, method: "GET", url: root_path, remote: true do |form|%>
      <%= form.input :modes, label: "Modes : ", collection: $modes, as: :check_boxes%>
      <%= form.input :durations, label: "Duration : ", collection: $durations, as: :check_boxes %>
    <% end %>

</div>

app/views/trainings/_new_comment_form.html.erb
<div class="new_comment">
  <div class="current_user_avatar">
    <% if current_user %>
      <% if current_user.picture.attached? %>
        <%= image_tag current_user.picture %>
      <% else %>
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="64x64" class="mr-2 rounded" style="width: 64px; height: 64px;" src="https://previews.123rf.com/images/salamatik/salamatik1801/salamatik180100019/92979836-ic%C3%B4ne-de-visage-anonyme-de-profil-personne-silhouette-grise-avatar-par-d%C3%A9faut-masculin-photo-placeholder-.jpg" data-holder-rendered="true">
      <% end %>
    <% else %>
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 64px; height: 64px;" src="https://previews.123rf.com/images/salamatik/salamatik1801/salamatik180100019/92979836-ic%C3%B4ne-de-visage-anonyme-de-profil-personne-silhouette-grise-avatar-par-d%C3%A9faut-masculin-photo-placeholder-.jpg" data-holder-rendered="true">
    <% end %>
  </div>
  <%= form_tag "/comments", method: "post" do %>
    <textarea name="content" class="form-control" placeholder="Ecris ton commentaire"></textarea>
    <input type="submit" value="Envoyer"/>
    <input type="hidden" name="training_id" value="<%= @training.id %>"/>
  <% end %>
</div>

app/views/trainings/_trainings.html.erb
<div class="container-fluid red">

  <div class="container green">
    <div class="row pt-3 m-auto yellow">
      <% if @trainings %>
       <% @trainings.each do |training|%>
        <article class ="col-xs-12 col-sm-12 col md-4 col-lg-4 p-2 card-index">


            <div class="card card-custom bg-white border-white border-5" style="height: 450px">
            <div class="card-custom-img" style="background-image: url(<%= training.background_img %>);"></div>

            <div class="card-custom-avatar">
              <img class="img-fluid" src="<%= training.school.logo_url %>" alt="Avatar">

            </div>
            <div class="card-body" style="overflow-y: auto">
              <p><%= training.school.name %></p>
              <h4 class="card-title"> <%= training.name %></h4>
              <p class="card-text" style="text-align: justify;"><%=training.description%>
              </p>
            </div>


              <div class="container justify ">
                  <div class="footer">



            <div class="toast-body ">
              <ul>
              <li class="badge badge-warning"><%= training.mode %></li>
              <% if training.sessions.first %>
                <li class="badge badge-danger"><%= training.sessions.first.price.to_i %> €</li>
              <% end %>
              <li class="badge badge-info"><%= training.duration.to_i %> semaines</li>
              </ul>
            </div>
            </div>
            </div>


            <div class="card-footer" style="background: ; border-color: ;">


               <%= link_to "Voir la formation", school_training_path(training.school_id, training.id), class: "btn btn-success btn-lg btn-block" %>

            </div>
          </div>
        </article>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/trainings/index.html.erb
<div class="container col-12 mt-5">
  <div class="text-center filters">
    <h4>Filtres de recherche : </h4>
    <br>
    <%= render 'filter_mode' %>
  </div>

  <div class="items-list d-flex flex-wrap mt-5 trainings">
    <%= render 'trainings', trainings: @trainings %>

  </div>
</div>

<script type="text/javascript">
  var checkBoxes = document.querySelectorAll(".check_boxes");

  var form = document.querySelector('.simple_form');

  for (const checkBox of checkBoxes) {
  checkBox.addEventListener( 'change', function() {
    Rails.fire(form, 'submit');
  });
  }
</script>

app/views/trainings/index.js.erb
function replaceTrainings (innerHTML) {
  const trainings = document.querySelector('.trainings');
  trainings.innerHTML = innerHTML;
}


if ('<%= @filter %>' === "[]") {
replaceTrainings("<%= j render 'trainings', trainings: Training.all %>");
}
else {
replaceTrainings("<%= j render 'trainings', trainings: @trainings %>");
}

app/views/trainings/new.html.erb
<div class="jumbotron-2">
  <div class="container green ">
      <div class="header-form ">
        
      <b>Publiez votre formation</b>
       </div>
       <div class="container col-sm-8 btn-holer yellow">


              <div class="bg-white col-sm-8 rounded shadow p-3 red">
              <%= form_with model: Training.new, url: "/schools/#{params[:school_id]}/trainings" do |form| %>

              <div class="form-group">
                  <%= form.label :nom %>:<br />
                  <%=form.text_field :name, class: 'form-control', placeholder: 'Nom de la formation'%>
                </div>
                <div class="form-group">
                    <%= form.label 'Durée de la formation (en semaines)' %>:
                    <%= select_tag(:duration ,options_for_select(['1', '2', '3', '4', '5', '6']), class: 'form-control') %>
                </div>

                <div class="form-group">
                  <%= form.label :description %> :<br />
                  <%=form.text_field :description, class: 'form-control', placeholder: 'Présentez votre formation...'%>
                </div>

                <div class="form-group">
                  <%= form.label 'Nombre d\'heures minimum par jour' %>:
                  <%= select_tag(:hours_per_day ,options_for_select(['2', '3', '4', '6', '8']), class: 'form-control') %>
                </div>
                <div class="form-group">
                  <%= form.label :url %>:<br />
                  <%=form.text_field :url, class: 'form-control', placeholder: 'www.mon_école.com'%>
                </div>
                <div class="form-group">
                    <%= form.label 'Mode d\'enseignement' %>:
                    <%= select_tag(:mode ,options_for_select(['Présentiel', 'À distance', 'Présentiel ou à distance', 'Alternance', 'Autre']), class: 'form-control') %>
                </div>
                <fieldset class="form-group">
                    <label>Aide à la recherche d'emploi :</label>

                    <div class="form-check">
                    <%= radio_button_tag(:help_for_a_job, true) %>
                    <%= label_tag(:true, "Oui") %><br>
                    <%= radio_button_tag(:help_for_a_job, false) %>
                    <%= label_tag(:false, "Non") %>
                </fieldset>
                  <hr>
                <div class="actions">
                  <%= form.submit "Envoyer", class: 'btn btn-success btn-lg btn-block' %>
                </div>

              <% end %>
                 
              </div>
          


        </div>
    </div>

</div>
    

app/views/trainings/show.html.erb
<div class="training">
  <div class="jumbotron" style="background-image: url(<%= @training.background_img %>); background-size: cover; background-position: center center;">
    <span class="display-5 text-white"><%= @training.name %></span>
    <hr class="my-4">
    <span class="display-5 text-warning"><%= @training.school.name %></span>
  </div>
    <div class="container green">
      <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <a class="nav-item nav-link" id="nav-program-tab" data-toggle="tab" href="#nav-program" role="tab" aria-controls="nav-program" aria-selected="true">Programme</a>
          <a class="nav-item nav-link" id="nav-session-tab" data-toggle="tab" href="#nav-session" role="tab" aria-controls="nav-session" aria-selected="false">Sessions</a>
          <a class="nav-item nav-link" id="nav-school-tab" data-toggle="tab" href="#nav-school" role="tab" aria-controls="nav-school" aria-selected="false">L'école</a>
          <a class="nav-item nav-link" id="nav-info-tab" data-toggle="tab" href="#nav-info" role="tab" aria-controls="nav-info" aria-selected="false">En savoir plus</a>
        </div>
      </nav>
    </div>


  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade active show" id="nav-program" role="tabpanel" aria-labelledby="nav-program-tab">
      <div class="card text">
        <div class="card-body">
          <% if @programs %>
            <% @programs.each do |program| %>
              <p><%= @program.description %></p>
              <p><strong>Les languages clés: </strong> <%= @program.language %></p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-session" role="tabpanel" aria-labelledby="nav-session-tab">
      <div class="row">
        <% if @sessions %>
          <% @sessions.each do |session| %>
            <% if session.start_date && session.end_date %>
              <div class="col">
                <div class="card-header border-secondary mb-3"> Sessions à venir
                </div>
                <div class="card-body">
                  <p class="card-text"><p><i class="fa fa-calendar-check-o" aria-hidden="true"></i><%=  " Commence le : #{session.start_date.strftime('%d/%m/%y')}" %></p>
                  <p><i class="fa fa-calendar-times-o" aria-hidden="true"></i><%= " Finit le : #{session.end_date.strftime('%d/%m/%y')}"%></p>
                  <p><i class="fa fa-map-marker" aria-hidden="true"></i><%= "    #{session.location}" %></p>
                  <p><i class="fa fa-eur" aria-hidden="true"></i><%= "#{session.price.to_i}" %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <p>Pas de sessions de prévues...</p>
        <% end %>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-school" role="tabpanel" aria-labelledby="nav-school-tab">

      <div class="card text-center">
        <div class="card-body">
          <h4 class="card-title" style="text-align:center"><%= @training.school.name %></h4>
          <img src="<%= @training.school.logo_url %>" alt="@training.school.website" class="  img-thumbnail" width="200" height="232" style="float:center">
          <p class="card text-center">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Nombre de campus : <%= @training.school.campus_nb %></li>
            <li class="list-group-item">Date de création : <%= @training.school.creation_year %></li>
            <li class="list-group-item"><%= link_to "Site web de l'école", @training.school.website, class: "btn btn-link" %></li>
          </ul>
          </p>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-info" role="tabpanel" aria-labelledby="nav-info-tab">
      <div class="col-12 text-center"> 
        <%= link_to "Aller sur le site de la formation", @training.url, class: "btn btn-info"%>
      </div>

      <br>
    </div>
  </div>
  <br>

  <div class="comments">
    <%= render 'comments' %>
    <%= render 'new_comment_form' %>
  </div>
</div>