config/routes.rb
Rails.application.routes.draw do

  resources :admin
  resources :schools do
    resources :trainings, except: [:index]
  end
  resources :trainings, only: [:index]

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, only: [:edit] do
    resources :pictures, only: [:create]
  end

  resources :comments

  root 'staticpages#home'

  get "/staticpages" => "staticpages#guide"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :training
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :training
end

app/models/school.rb
class School < ApplicationRecord
  has_many :trainings
  belongs_to :user 
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :training
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :school
  has_many :comments
  has_many :sessions
  has_many :programs

  acts_as_taggable_on :tags

  $modes = ["à distance", "présentiel", "à distance et en alternance", "à distance ou présentiel"]
  $durations = ["1-10", "11-20", "21-30", "31-40", "41+"]
  $prices = [ "0-1000", "1001-2000", "2001-3000", "3001-4000", "4000+"]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_one_attached :picture
  after_create :welcome_send

  has_one :school

  def full_name
    self.first_name + " " + self.last_name
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @user = User.find_by(id: current_user.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new

  end

  def create
    if current_user
      @comment = Comment.new(content: params[:content],user_id: current_user.id, training_id: params[:training_id])
      if @comment.save
        flash[:success] = "The comment has been added."
        redirect_to school_training_path(Training.find(params[:training_id]).school_id, params[:training_id])
      else
        flash[:danger] = "The comment has not been added."
        redirect_to school_training_path(Training.find(params[:training_id]).school_id, params[:training_id])
      end
    else
      flash[:danger] = "Connect to comment."
      redirect_to new_user_registration_path
    end
  end

  def edit
    @comment = Comment.find(params[:id])

  end

  def update
    @comments = Comment.all
    @comment = Comment.find(params[:id])
    @training = Training.find(@comment.training.id)
    if current_user
      @comment.update(content: params[:content])
      if @comment.save
        flash[:success] = "The comment has been edited."
        redirect_to school_training_path(params[:school_id], params[:training_id])
      else
        flash[:danger] = "The comment has not been edited."
        redirect_to school_training_path(params[:school_id], params[:training_id])
      end
    else
      flash[:danger] = "Connect to edit."
      redirect_to new_user_registration_path
    end
  end

  def index
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = "The comment has been deleted."
    redirect_to school_training_path(Training.find(params[:training_id]).school_id, params[:training_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    if params[:picture]
      @user = current_user
      @user.picture.attach(params[:picture])
      redirect_to edit_user_password_path
      flash[:success] = "Votre image de profil a été mise à jour."
    else
      flash[:danger] = "Vous n'avez pas inséré d'image."
      redirect_to edit_user_password_path
    end
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  def new
    @school = School.new
    if signed_in?
      if current_user.is_school === true
        redirect_to new_school_training_path(:school_id)
      end
    else
      redirect_to new_user_registration_path, info: "Pour renseigner vos formations en temps qu'école vous devez vous connecter ou vous inscrire."
    end
  end

  def create
    School.create(name: params[:school][:name], website: params[:school][:website], creation_year: params[:school][:creation_year].to_i, campus_nb: params[:school][:campus_nb].to_i, siret: params[:school][:siret], user_id: current_user.id)
    become_a_school
    @school = School.find_by(website: params[:school][:website])
    redirect_to new_school_training_path(@school.id), success: "Ce compte est désormais un compte École !"
  end

  private
  def become_a_school
    current_user.update(is_school: true)
  end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/admin/_school_trainings.html.erb
<div class="btn-group-vertical ml-2">
  <% @user.school.trainings.each do |training| %>
  <%=button_to training.name, school_training_path(training.school_id, training), method: "get" ,class: "btn btn-primary mb-1"%>
  <% end %>
</div>

app/views/admin/index.html.erb
<div class="container-fluid bg-light text-center">
  <h1> <%= @user.school.name %> </h1>
  <h3> Vous avez <%= @user.school.trainings.count %> formation<%if @user.school.trainings.size > 1%>s<%end%></h3>
  <hr>
</div>

<div class="ml-2 d-flex row">

  <%= render 'school_trainings', user: @user %>

  <div class="ml-auto mr-5">
    <%= button_to "Mes informations", edit_user_registration_path, method: "get",class: "btn btn-info" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small bg-primary">

      <!-- Footer Links -->
      <div class="container text-center text-md-left mt-5 footer-header">

        <!-- Grid row -->
        <div class="row">

          <!-- Grid column -->
          <div class="col-md-9 col-lg-9 col-xl-9 mx-auto mb-4">

            <!-- Content -->
            <h6 class="text-uppercase font-weight-bold footer-text footer-header">© Reconversion Web Pro</h6>
            <hr class="footer-line accent-2 mb-4 mt-0 d-inline-block mx-auto footer-text" style="width: 60px;">
            <p>La meilleure solution pour trouver la formation Web la plus adaptée à son profil</p>

          </div>
          <!-- Grid column -->


          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

            <!-- Links -->
            <h6 class="text-uppercase font-weight-bold footer-text footer-header">Contact</h6>
            <hr class="footer-line accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>contact@reconversion-web-pro.com</p>



          </div>
          <!-- Grid column -->

        </div>
        <!-- Grid row -->

      </div>
      <!-- Footer Links -->

      <!-- Copyright -->
      <div class="footer-copyright text-center py-3 footer-text">© 2020 Copyright: Reconversion Web Pro
        <a href="#" class = "footer-text">Equipe THP</a>
      </div>
      <!-- Copyright -->

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetFinal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>


    <!-- Flatly : Bootswatch theme -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha384-mhpbKVUOPCSocLzx2ElRISIORFRwr1ZbO9bAlowgM5kO7hnpRBe+brVj8NNPUiFs" crossorigin="anonymous">


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <script src="https://use.fontawesome.com/e329530bc6.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>


    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">


      <div class="logorwp">
        <%= link_to root_path do %>
          <%= image_tag("propositionlogo2.png", size: "140x60") %>
        <% end %>
      </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <div class="nav-item" id="element1">
            <%= link_to "Les formations", trainings_path, class: "nav-link" %>
          </div>

          <div class="nav-item" id="element4">
            <%= link_to "Foire Aux Questions", staticpages_path , :class => "nav-link" %>
          </div>

          <div class="nav-item" id="element3">
            <%= link_to "Espace école", new_school_path, class: "nav-link" %>
          </div>
        </ul>
      </div>

      <div class="navbar_profile">
        <% if signed_in? %>
          <% if current_user.picture.attached? %>
            <%= image_tag current_user.picture, class: "navbar_profile_picture" %>
          <% end %>

          <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
            <div class="btn-group" role="group">
              <button id="btnGroupDrop4" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= image_tag("user.png", size: "30x30") %>Mon compte</button>
              <div class="dropdown-menu" aria-labelledby="btnGroupDrop4" style="">
                <% if current_user.is_school === true %>
                  <%= link_to "Mes informations", admin_index_path %>
                <% else %>
                  <%= link_to "Mes informations", edit_user_registration_path %>
                <% end %>
                        <br>
                <%= link_to "Me déconnecter", destroy_user_session_path, method: :delete%>
                </div>
            </div>
          </div>

        <% else %>

          <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
            <div class="btn-group" role="group">
              <button id="btnGroupDrop4" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Se connecter / S'inscrire</button>
                <div class="dropdown-menu" aria-labelledby="btnGroupDrop4" style="">
                  <%= link_to "Me connecter", new_user_session_path%><br>
                  <%= link_to "M'inscrire", new_user_registration_path%>
                </div>
            </div>
          </div>

        <% end %>

      </div>

    </nav>

  <body>
      <%= render 'flash_messages'%>

      <%= yield %>

     <%= render 'layouts/footer' %>
  </body>
</html>